apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-role
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - services
      - secrets
      - persistentvolumeclaims
      - resourcequotas
      - limitranges
      - pods
    verbs: ["create", "get", "list", "delete", "watch", "update", "patch"]

  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - replicasets
    verbs: ["create", "get", "list", "delete", "watch", "update", "patch"]

  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - networkpolicies
    verbs: ["create", "get", "list", "delete", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: platform-role
  apiGroup: rbac.authorization.k8s.io